name: Test
on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master, 'peah/*']
  create:

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Create release draft for a version tag
        id: create-release-draft
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-token: ${{ github.ref }}

      - name: Print the URL of the release draft
        id: print-release-url
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
        
